import {describe, expect, test} from '@jest/globals';
import { getSumOfTheLength } from './excerise1';

describe('Day 11 --> Excerise 1', () => {
  test('should returns 0 when string is empty', () => {
    expect(getSumOfTheLength(''))
      .toBe(0);
  });
  test('should returns 374 when galxies is doubled', () => {
    expect(getSumOfTheLength(`...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....`))
      .toBe(374);
  });
  test('should returns 1030 when galxies is increased by 10times', () => {
    expect(getSumOfTheLength(`...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....`, 10))
      .toBe(1030);
  });

  test('should returns 1030 when galxies is increased by 10times', () => {
    expect(getSumOfTheLength(`...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....`, 100))
      .toBe(8410);
  });
});